compose:
  zookeeper:
    image: jplock/zookeeper
  mesos-master:
    image: mesosphere/mesos-master:0.26.0-0.2.145.ubuntu1404
    environment:
      - MESOS_ZK=zk://localhost:2181/mesos
      - MESOS_HOSTNAME=localhost
      - MESOS_QUORUM=1
      - MESOS_REGISTRY=in_memory
  mesos-slave:
    image: mesosphere/mesos-slave-dind:0.2.4_mesos-0.26.0_docker-1.8.2_ubuntu-14.04.3
    environment:
      - MESOS_MASTER=zk://localhost:2181/mesos
      - MESOS_HOSTNAME=localhost
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_WORK_DIR=/tmp/satyr/mesos
      - MESOS_STRICT=false
    volumes:
      - /tmp/satyr/mesos:/tmp/satyr/mesos
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true


build:
  image: lensa/mesos-python:0.26.0-py2.7-python-2.7
  environment:
    - SATYR_MASTER=zk://localhost:2181/mesos
  commands:
    #- easy_install http://downloads.mesosphere.io/master/debian/8/mesos-0.26.0-py2.7-linux-x86_64.egg
    #- pip install --process-dependency-links -e .
    #- pip install pytest
    - python setup.py test
